apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config
data:
    nginx.conf: |
        events {}
        http {
            server {
                listen 8080;
                server_name https://todo-plvv.onrender.com ;
        
                location / {
                    proxy_pass https://todo-plvv.onrender.com;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }
        }
